version: '3.7'

services:
    #web:
    #    build:
    #    context: ./services/web
    #    dockerfile: Dockerfile.prod
    #    command: gunicorn --log-level debug --bind 0.0.0.0:5000 manage:app
    #    volumes:
    #    - static_volume:/home/app/web/web_app/static
    #    - media_volume:/home/app/web/web_app/media
    #    expose:
    #    - 5000
    #    env_file:
    #    - ./.env.common
    #    - ./.env.prod
    #depends_on:
    #  - db
    #db:
    #    image: postgres:12-alpine
    #    volumes:
    #        - postgres_data:/var/lib/postgresql/data/
    #    env_file:
    #        - ./.env.prod.db  
     
    proxy:
        build:
          context: ./services/proxy
        command: python smarthome_proxy.py
        #volumes:
        #  - static_volume:/home/app/web/web_app/static
        #  - media_volume:/home/app/web/web_app/media
        #expose:
        #  - 5000
        #env_file:
        #  - ./.env.common
        #  - ./.env.prod
        #depends_on:
        #  - db

