version: '3.8'

services:
  proxy:
    build:
      context: ./services/proxy
    command: python smarthome_proxy.py
    volumes:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - ./services/proxy/:/usr/src/app/
      - json_data:/usr/src/app/json_data/
    environment:
      DOCKER: 1
    privileged: True
     
  web:
    build: 
      context: ./services/web
    command: python SmartHomeWebserver.py --dir public_html --https 8000 user:pass
    ports:
      - "8000:8000"
    volumes:
      - json_data:/usr/src/app/public_html/json_data/


volumes:
  json_data: 