version: '3.8'

services:
  relay:
    build:
      context: ./services/relay
      network: host
    command: python smarthome_relay.py
    volumes:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - ./services/relay/:/usr/src/app/
      - json_data:/usr/src/app/json_data/
    ports:
      - "45321:45321"
    environment:
      DOCKER: 1
    privileged: True
    network_mode: host 
    restart: always
     
  web:
    build: 
      context: ./services/web
    ports:
      - "3000:3000"
    volumes:
      - json_data:/usr/src/app/public_html/json_data/
    restart: always


volumes:
  json_data: 
